version: "3"
services:
  jenkins:
    container_name: jenkins
    image: elissa71/jenkins-with-docker
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - /Users/notju:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins
networks:
  jenkins: